### ISSUE TITLE
Speech to text not working

### ISSUE THREAD

**Issue by kif01** [Najibsaurus/VoiceBot-Watson#1]
Hey Najib, so I cloned the code and added my credentials, but when I record my voice, the voice's length is 0 and I get this following error: Error: { Error: Stream was 44 bytes but needs to be at least 100 bytes.

**Comment by Najibsaurus** [comment]
Hi @kif01 , thanks for reaching out.
Are you using Google Chrome as your browser ?
The issue cause the policy of playing audio file on it. You could check the audio policiy in [here](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes) 

So, you need to add the code on /js/audio.js on line 16 :
```
var onSuccess = function (stream) {
  audioContext.resume();
  inputPoint = audioContext.createGain();
  audioInput = audioContext.createMediaStreamSource(stream);
  audioInput.connect(inputPoint);
  recorder = new Recorder(inputPoint);
  recorder.clear();
  recorder.record();
};
```

Regards,

**Comment by kif01** [comment]
Thank you!
